/////////////////////////////////////////////////////////////
// cxr_test.h
//
// This file was generated by CXR, the literal string encryptor.
// CXR, Copyright 2002, Smaller Animals Software, Inc., all rights reserved.
//
// Please do not edit this file. Any changes here will be overwritten on the next compile.
// If you wish to make changes to a string, please edit:
//     test.cxr
//

/////////////////////////////////////////////////////////////

#pragma once
#include "cxr_inc.h"

// cxr 적용 테스트입니당

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST1 	_CXR("\x8b\x85\x8d\x81\x83\x8e\x87\x89\x85\x87\x8e\x84\x83\x8c\x89\x83\x8a\x86\x88\x81\x84\x8c\x8a\x81\x88\x84\x8e\x81\x8c\x89\x81\x88\x8a\x81\x8d\x80\x8b\x85\x81\x8c\x80\x89\x84\x89\x8c\x80\x81\x87\x86\x8a\x88\x83\x83\x81\x8c\x8b\x85\x8f\x8f\x89\x8a\x88\x8d\x87\x80\x8e")
#else
#define STR_CXRTEST1 _CXR("Your all bases are belong to us.")
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST2 	_CXR("\x84\x8b\x84\x8e\x89\x8d\x86\x8c\x89\x80\x8e\x8c\x8f\x8c\x8e\x8c\x89\x83\x81\x83")// 디파인 뒤에 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST2 _CXR("It's You!")// 디파인 뒤에 주석이 달린 경우를 테스트
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST3 	_CXR("\x84\x89\x83\x83\x83\x8e\x86\x81\x88\x88")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST3 _CXR("Aye.")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#endif


