#ifndef __HanAuthForClient__
#define __HanAuthForClient__

#ifdef HANAUTHFORCLIENT_EXPORTS
	#define HANAUTH_API __declspec(dllexport)
#else
	#ifdef _DEBUG
	#else
		#pragma comment(lib, "HanAuthForClient.lib") 
	#endif
#endif

#define SIZE_AUTHSTRING			2048
#define SIZE_GAMESTRING			4096

#define SERVICE_NATION			0x000000FF
#define SERVICE_KOR				0x00000001
#define SERVICE_USA				0x00000002
#define SERVICE_JPN				0x00000003
#define SERVICE_CHN				0x00000004

#define SERVICE_TYPE			0x00000F00
#define SERVICE_ALPHA			0x00000100
#define SERVICE_REAL			0x00000200
#define SERVICE_BETA			0x00000300

#define SERVICE_SITE			0x0000F000
#define SERVICE_HANGAME			0x00001000
#define SERVICE_ASOBLOG			0x00002000
#define SERVICE_IJJI			0x00003000
#define SERVICE_GAMETAP			0x00004000

#define REFRESH_MAXFAIL			3

#define USA_REFRESH_RET_VARS	4

#define HAN_AUTHCLI_OK								0
#define HAN_AUTHCLI_ARGUMENT_INVALID				-1
#define HAN_AUTHCLI_INITED_ALREADY					-2
#define HAN_AUTHCLI_INITED_NOT						-3
#define HAN_AUTHCLI_INITED_FAIL						-4
#define HAN_AUTHCLI_AUTHHTTP_INITFAIL				-5
#define HAN_AUTHCLI_AUTHHTTP_CONNFAIL				-6
#define HAN_AUTHCLI_REFRESHHTTP_INITFAIL			-7
#define HAN_AUTHCLI_REFRESHHTTP_CONNFAIL			-8
#define HAN_AUTHCLI_NOT_IMPLEMENTED					-9
#define HAN_AUTHCLI_AUTHHTTP_OPENREQFAIL			-10
#define HAN_AUTHCLI_AUTHHTTP_SENDREQFAIL			-11
#define HAN_AUTHCLI_COOKIE_SETFAIL					-13
#define HAN_AUTHCLI_GAMESTRING_IDINVALID			-14
#define HAN_AUTHCLI_GAMESTRING_USNINVALID			-15
#define HAN_AUTHCLI_GAMESTRING_GAMEIDINVALID		-16
#define HAN_AUTHCLI_GAMESTRING_SERVICECODEINVALID	-17
#define HAN_AUTHCLI_CREATEINTANCEFAIL				-18

#define HAN_AUTHCLI_DLL_UNEXPECTED		 -100

#define HAN_AUTHCLI_PARAM_INVALID			1
#define HAN_AUTHCLI_IPADDR_INVALID			2
#define HAN_AUTHCLI_MEMBERID_INVALID		3
#define HAN_AUTHCLI_PASSWORD_INCORRECT		4
#define HAN_AUTHCLI_PASSWORD_MISMATCHOVER	5
#define HAN_AUTHCLI_MEMBERID_NOTEXIST		6
#define HAN_AUTHCLI_SYSTEM_ERROR			7
#define HAN_AUTHCLI_COOKIE_SETERROR			8



#endif  