#ifndef ZACTIONDEF_H
#define ZACTIONDEF_H

const enum
{
	ZACTION_USE_WEAPON = 0,
	ZACTION_USE_WEAPON2,

	ZACTION_PREV_WEAPON,
	ZACTION_NEXT_WEAPON,

	ZACTION_FORWARD,
	ZACTION_BACK,
	ZACTION_LEFT,
	ZACTION_RIGHT,
	ZACTION_MELEE_WEAPON,
	ZACTION_PRIMARY_WEAPON,
	ZACTION_SECONDARY_WEAPON,
	ZACTION_ITEM1,
	ZACTION_ITEM2,
	ZACTION_ITEM3,
	ZACTION_COMMUNITYITEM1,
	ZACTION_COMMUNITYITEM2,

	ZACTION_RELOAD,
	ZACTION_JUMP,
	ZACTION_SCORE,
	ZACTION_MENU,
	
	ZACTION_TAUNT,
	ZACTION_BOW,
	ZACTION_WAVE,
	ZACTION_LAUGH,
	ZACTION_CRY,
	ZACTION_DANCE,
	
	ZACTION_SCREENSHOT, 
	ZACTION_RECORD,
	ZACTION_MOVING_PICTURE, 
	
	ZACTION_DEFENCE,
	ZACTION_TOGGLE_CHAT,

	ZACTION_SHOW_FULL_CHAT,
	ZACTION_CHAT,
	ZACTION_TEAMCHAT,
	ZACTION_VOICE_CHAT,

	ZACTION_SENSITIVITY_DEC,
	ZACTION_SENSITIVITY_INC,
	ZACTION_SONG_NEXT,
	ZACTION_SONG_PREVIOUS,

	///BlitzKrieg
	ZACTION_UPGRADELIST,
	ZACTION_HELP,
	ZACTION_NEWERWEAPON, // what does this mean?
	ZACTION_NEWERBULLET,
	ZACTION_NEWERARMOR,
	ZACTION_INCENDIARY,
	ZACTION_LARGERMAGAZINE,
	ZACTION_PRIVATEMEDIC,


	ZACTION_COUNT
};

#endif